#include "Config.h"
#include <fstream>
#include <sstream>

Config g_config; // Global instance

Config::Config() {
    configFilePath = "plugin_config.ini";
    setDefaults();
    loadFromFile();
}

void Config::setDefaults() {
    // Feature toggles
    boolSettings["lobby_logging_enabled"] = true;
    boolSettings["netvar_dump_enabled"] = false;
    boolSettings["debug_logging_enabled"] = true;
    boolSettings["esp_enabled"] = false;
    boolSettings["renderer_self_test_enabled"] = false;
    boolSettings["display_module_list"] = true;
    boolSettings["airstuck_enabled"] = false;
    boolSettings["speed_enabled"] = false;
    boolSettings["aimbot_enabled"] = false;
    boolSettings["datamap_dump_enabled"] = false;
    
    // Intervals (in frames)
    intSettings["lobby_log_interval"] = 10000;  // Every 1000 frames
    
    // File paths
    stringSettings["lobby_log_file"] = "lobby_players.txt";
    stringSettings["plugin_name"] = "CppPluginExample";
    stringSettings["title"] = "nh";

    floatSettings["speed"] = .25f;
    floatSettings["aimbot_fov"] = 8.0f;
    floatSettings["aimbot_smooth"] = 4.0f;
}

void Config::loadFromFile() {
    std::ifstream file(configFilePath);
    if (!file.is_open()) {
        // Config file doesn't exist, create it with defaults
        saveToFile();
        return;
    }
    
    std::string line;
    while (std::getline(file, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }
        
        // Parse key=value pairs
        size_t equalPos = line.find('=');
        if (equalPos == std::string::npos) {
            continue;
        }
        
        std::string key = line.substr(0, equalPos);
        std::string value = line.substr(equalPos + 1);
        
        // Trim whitespace
        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);
        
        // Parse by known key type so float settings are handled correctly.
        try {
            if (boolSettings.find(key) != boolSettings.end()) {
                boolSettings[key] = (value == "true");
            } else if (intSettings.find(key) != intSettings.end()) {
                intSettings[key] = std::stoi(value);
            } else if (floatSettings.find(key) != floatSettings.end()) {
                floatSettings[key] = std::stof(value);
            } else if (value == "true" || value == "false") {
                boolSettings[key] = (value == "true");
            } else if (value.find_first_of(".eE") != std::string::npos) {
                floatSettings[key] = std::stof(value);
            } else if (value.find_first_not_of("0123456789-") == std::string::npos) {
                intSettings[key] = std::stoi(value);
            } else {
                stringSettings[key] = value;
            }
        } catch (...) {
            // Ignore invalid value lines and keep defaults.
        }
    }
    
    file.close();
}

void Config::saveToFile() {
    std::ofstream file(configFilePath);
    if (!file.is_open()) {
        return;
    }
    
    file << "# Plugin Configuration File\n";
    file << "# This file is automatically generated\n";
    file << "# You can edit values and they will be loaded on plugin restart\n\n";
    
    file << "# Feature Toggles\n";
    for (const auto& pair : boolSettings) {
        file << pair.first << "=" << (pair.second ? "true" : "false") << "\n";
    }
    
    file << "\n# Numeric Settings\n";
    for (const auto& pair : intSettings) {
        file << pair.first << "=" << pair.second << "\n";
    }

    file << "\n# Float Settings\n";
    for (const auto& pair : floatSettings) {
        file << pair.first << "=" << pair.second << "\n";
    }
    
    file << "\n# String Settings\n";
    for (const auto& pair : stringSettings) {
        file << pair.first << "=" << pair.second << "\n";
    }
    
    file.close();
}

bool Config::getBool(const std::string& key) {
    auto it = boolSettings.find(key);
    return (it != boolSettings.end()) ? it->second : false;
}

void Config::setBool(const std::string& key, bool value) {
    boolSettings[key] = value;
}

int Config::getInt(const std::string& key) {
    auto it = intSettings.find(key);
    return (it != intSettings.end()) ? it->second : 0;
}

void Config::setInt(const std::string& key, int value) {
    intSettings[key] = value;
}

float Config::getFloat(const std::string& key) {
    auto it = floatSettings.find(key);
    return (it != floatSettings.end()) ? it->second : 0.0f;
}

void Config::setFloat(const std::string &key, float value) {
    floatSettings[key] = value;
}

std::string Config::getString(const std::string& key) {
    auto it = stringSettings.find(key);
    return (it != stringSettings.end()) ? it->second : "";
}

void Config::setString(const std::string& key, const std::string& value) {
    stringSettings[key] = value;
}

void Config::reload() {
    setDefaults();
    loadFromFile();
}

void Config::save() {
    saveToFile();
}

void Config::logCurrentSettings() {
    if (!g_nssys || !g_handle) return;
    
    g_nssys->Log(g_handle, LogLevel::INFO, "=== Plugin Configuration ===");
    
    for (const auto& pair : boolSettings) {
        g_nssys->Log(g_handle, LogLevel::INFO, 
                     fmt::format("{}: {}", pair.first, pair.second ? "enabled" : "disabled").c_str());
    }
    
    for (const auto& pair : intSettings) {
        g_nssys->Log(g_handle, LogLevel::INFO, 
                     fmt::format("{}: {}", pair.first, pair.second).c_str());
    }

    for (const auto& pair : floatSettings) {
        g_nssys->Log(g_handle, LogLevel::INFO,
                     fmt::format("{}: {:.3f}", pair.first, pair.second).c_str());
    }
    
    g_nssys->Log(g_handle, LogLevel::INFO, "==============================");
}
